### ISSUE TITLE
Roadmap and ideas

### ISSUE THREAD

**Issue by sreimers** [baresip/baresip-libs#2]
- [x] Add re/rem/retest as git subtree folders (Temporarily)
- [x] Add CMake
- [ ] Add Github Actions/Workflows
- [ ] Create Baresip PR
- [ ] Create announcement and archive old repos
